server:
  port: 10010
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
zuul:
  routes:
    manager-web:
      path: /manager/**
      serviceId: sellergoods-service